### PR TITLE
Clang format

### PR DESCRIPTION
**Pull request by darcys22**

### CODE REVIEW

**Comment by majestrate** [comment]
cant wait to see the face on @tewinget in the morning when he sees this.

**Comment by tewinget** [comment]
I didn't look at literally every line, but LGTM

**Comment by fracting** [comment]
> I didn't look at literally every line, but LGTM

I guess a reviewer can manually revert to a previous commit and run clang format locally to compare if the output is identical to the patch being reviewed. Otherwise, such kind of big change is a great opportunity of introducing malicious code if it's not from a trusted member. No offensive, just a theoretical discussion of potential supply chain attacks. [1]

[1] https://www.semanticscholar.org/paper/On-the-Feasibility-of-Stealthily-Introducing-in-via-Wu-Lu/0d8049e0614ed1c5dc7b5add4ccacdfe4535bf9c

**Comment by majestrate** [comment]
> > I didn't look at literally every line, but LGTM
> 
> I guess a reviewer can manually revert to a previous commit and run clang format locally to compare if the output is identical to the patch being reviewed. Otherwise, such kind of big change is a great opportunity of introducing malicious code if it's not from a trusted member. No offensive, just a theoretical discussion of potential supply chain attacks. [1]
> 
> [1] https://www.semanticscholar.org/paper/On-the-Feasibility-of-Stealthily-Introducing-in-via-Wu-Lu/0d8049e0614ed1c5dc7b5add4ccacdfe4535bf9c

we could put the reformat through the clang lexer and compare it with the previous revision's.

**Comment by majestrate** [comment]
> > I guess a reviewer can manually revert to a previous commit and run clang format locally to compare if the output is identical to the patch being reviewed. Otherwise, such kind of big change is a great opportunity of introducing malicious code if it's not from a trusted member. No offensive, just a theoretical discussion of potential supply chain attacks. [1]
> 
> We had exactly the same conversation internally; I believe @tewinget _did_ do exactly this before signing off on the PR.

can we document how it was done so others can do so themselves? (like myself)

**Review by jagerman — APPROVED** [review]

**Comment by jagerman** [comment]
The PR here wasn't formatting properly (i.e. running clang-format again changed it), and the lint job wasn't working.

Fixed, along with separating out the non-format changes and some other build/formatting fixes.

**Comment by tewinget** [comment]
Looks good to me as of 5436df9615635b4e7363a79caedd1db162f208ba.

**Comment by jagerman** [comment]
This is more reproducible/verifiable now: the entire reformatting is now confined to a single commit that *only* reformats (13409ad) while the changes before that and after that add the formatting machinery, and fixes due to the formatting, respectively.

**Pull request merged**
